language: groovy

jdk:
- oraclejdk6

before_install:
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- source ~/.gvm/bin/gvm-init.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- gvm install grails 2.2.0
- gvm use grails 2.2.0

branches:
  only:
    - master

script: grails test-app --non-interactive