language: groovy

jdk:
- oraclejdk6

before_install:
- curl -s get.gvmtool.net | bash
- gvm install grails 2.2.0
- gvm use grails 2.2.0
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config

branches:
  only:
    - master

script: grails test-app --non-interactive