language: groovy

jdk:
- oraclejdk6

before_install:
- curl -s get.gvmtool.net | bash
- gvm install 2.2.1
- gvm use 2.2.1
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config

branches:
  only:
    - master

script: grails test-app --non-interactive